services:
  cloudforest:
    build: .
    container_name: cloudforest
    ports:
      - "8080:80"
    volumes:
      - ${CLOUDFOREST_VOLUME}:/export
    environment:
      TS_CRA_PASSWORD: ${TS_CRA_PASSWORD}
      TS_CRA_USERNAME: ${TS_CRA_USERNAME}
      NONUSE: "nodejs,reports,proftp"
      GALAXY_CONFIG_CLEANUP: onsuccess
      GALAXY_DIESTINATIONS_DEFAULT: local_no_container
      GALAXY_SLOTS: 4

volumes:
  default-cloudforest-volume:
